name: CI

on:
  push:
    branches: "main"
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - "node_modules/**"
      - "dist/**"
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          LANGUAGES_TABLE_ID: ${{ secrets.LANGUAGES_TABLE_ID }}
          WRITING_SYSTEMS_TABLE_ID: ${{ secrets.WRITING_SYSTEMS_TABLE_ID }}
          NATIONS_TABLE_ID: ${{ secrets.NATIONS_TABLE_ID }}
          NEXT_PUBLIC_API_STRICT_ORIGIN: ${{ secrets.NEXT_PUBLIC_API_STRICT_ORIGIN }}
          NEXT_PUBLIC_API_ALLOWED_ORIGINS: ${{ secrets.NEXT_PUBLIC_API_ALLOWED_ORIGINS }}
          NEXT_PUBLIC_STORAGE_PREFIX: ${{ secrets.NEXT_PUBLIC_STORAGE_PREFIX }}
          NEXT_PUBLIC_STORAGE_VERSION: ${{ secrets.NEXT_PUBLIC_STORAGE_VERSION }}
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel . --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
